language: node_js
node_js:
  - stable
install:
  - npm install
script:
  # Lint last commit message from history
  - npx commitlint --from=HEAD~1
  - npm run lint:dts
  - npm run lint
  - npm run test:coverage
  - npm run build
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
notifications:
  email: false
