language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run cover
  - npm run build
after_script:
  - npm run coveralls
notifications:
  email: false
